language: node_js

node_js: 6

cache: yarn

script:
- yarn run lint
- yarn run flow
- yarn run flow-coverage

deploy:
  provider: npm
  email: jacobwgillespie@gmail.com
  api_key:
    secure: hNHjKfSrkyX1tOqxNjXE6DsINvmYcI1JLGwAUvzpzax7vDmxkRPsCwZTcL6uDqQMgA76OV2BaYXGQNaH1wDmOEgf9sdiT2qN8vpLSxsnldu//Jq1mLwkQEy6L5It4U3Nvn8KWnzJf9LhlDnVp2xArVVPquRK/k215hhNJV/mr+X3cmyLMABcAiZVYkVB7hERAGG6L392zA0Kx54IDg0r8SrMcBy0EWJB84clBPnFkMqgYwbbOogn2FTmZUWpIjLno4h5ifsaqt761QXFUOMi43e72G9j2IOK+GFy4uoY43+9VP6qa3xS10UmL30VaBsGqQDGTLTAmtzXDke0BHTQnYE2dwIo7+hCdNr08P3WAYd82gqCnoKKPjklcyErNYpFTs6o5PlJ6zaHarVsvbLoIH3lgiM2e04nezKr+dqq2OMpzuU1lZi7/29UBkFSJZhlfP8L93NTyeiwLlK1Xy9sTPBDGvRQiM59ECcUYE/ifV3ufy/5JevaGR8adffr4DULXSqozLTojZgJBOZ8V9MKthH1cJ0uziz1TEJwK+KjqXh+70Y8GHp/h1p9xIL6uLU3aIyewssLfruDbRIiisfxQIIYsA1H7wW7pOHVtdYfetXxalTBP11EwIrq1g0xU1UKqqOqaGwAMdMFPi06w1vxnX8HNvOREbmWROw1hzqkDp0=
  on:
    tags: true
    repo: the-obsidian/mc-discourse-sso
    branch: master
