// flow-typed signature: 6cb2111245d101b645dbba79ca705996
// flow-typed version: <<STUB>>/discourse-sso_v^1.0.3/flow_v0.50.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'discourse-sso'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'discourse-sso' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'discourse-sso/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'discourse-sso/index' {
  declare module.exports: $Exports<'discourse-sso'>;
}
declare module 'discourse-sso/index.js' {
  declare module.exports: $Exports<'discourse-sso'>;
}
declare module 'discourse-sso/test.js' {
  declare module.exports: $Exports<'discourse-sso/test'>;
}
