// flow-typed signature: 6f54d776a0ad89d3f1fb6f8993033d07
// flow-typed version: <<STUB>>/ect_v^0.5.9/flow_v0.50.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ect'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ect' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ect/lib/ect' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ect/index' {
  declare module.exports: $Exports<'ect'>;
}
declare module 'ect/index.js' {
  declare module.exports: $Exports<'ect'>;
}
declare module 'ect/lib/ect.js' {
  declare module.exports: $Exports<'ect/lib/ect'>;
}
